/*
 * generated by Xtext 2.25.0
 */
package org.lowcomote.panoptes.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link PanoptesXWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractPanoptesXWebModule extends DefaultWebModule {

}
