/*
 * generated by Xtext 2.25.0
 */
package org.lowcomote.panoptes.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.lowcomote.panoptes.ide.contentassist.antlr.internal.InternalPanoptesXParser;
import org.lowcomote.panoptes.services.PanoptesXGrammarAccess;

public class PanoptesXParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(PanoptesXGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, PanoptesXGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getPlatformAccess().getAlternatives(), "rule__Platform__Alternatives");
			builder.put(grammarAccess.getModelIOAccess().getAlternatives(), "rule__ModelIO__Alternatives");
			builder.put(grammarAccess.getDeploymentIOAccess().getAlternatives(), "rule__DeploymentIO__Alternatives");
			builder.put(grammarAccess.getAlgorithmAccess().getAlternatives(), "rule__Algorithm__Alternatives");
			builder.put(grammarAccess.getAlgorithmRuntimeAccess().getAlternatives(), "rule__AlgorithmRuntime__Alternatives");
			builder.put(grammarAccess.getAlgorithmExecutionAccess().getAlternatives(), "rule__AlgorithmExecution__Alternatives");
			builder.put(grammarAccess.getHigherOrderAlgorithmExecutionAccess().getAlternatives_7_0(), "rule__HigherOrderAlgorithmExecution__Alternatives_7_0");
			builder.put(grammarAccess.getHigherOrderAlgorithmExecutionAccess().getAlternatives_8_0(), "rule__HigherOrderAlgorithmExecution__Alternatives_8_0");
			builder.put(grammarAccess.getTriggerGroupAccess().getAlternatives_1(), "rule__TriggerGroup__Alternatives_1");
			builder.put(grammarAccess.getTemporalTriggerAccess().getAlternatives(), "rule__TemporalTrigger__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
			builder.put(grammarAccess.getStatisticalVariableTypeAccess().getAlternatives(), "rule__StatisticalVariableType__Alternatives");
			builder.put(grammarAccess.getFrequencyEnumAccess().getAlternatives(), "rule__FrequencyEnum__Alternatives");
			builder.put(grammarAccess.getParameterTypeAccess().getAlternatives(), "rule__ParameterType__Alternatives");
			builder.put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
			builder.put(grammarAccess.getModelAccess().getGroup_6(), "rule__Model__Group_6__0");
			builder.put(grammarAccess.getFeatureStoreAccess().getGroup(), "rule__FeatureStore__Group__0");
			builder.put(grammarAccess.getFeatureStoreAccess().getGroup_3(), "rule__FeatureStore__Group_3__0");
			builder.put(grammarAccess.getFeatureStoreAccess().getGroup_3_2(), "rule__FeatureStore__Group_3_2__0");
			builder.put(grammarAccess.getFeatureStoreAccess().getGroup_4(), "rule__FeatureStore__Group_4__0");
			builder.put(grammarAccess.getFeatureStoreAccess().getGroup_4_2(), "rule__FeatureStore__Group_4_2__0");
			builder.put(grammarAccess.getFeatureStoreAccess().getGroup_5(), "rule__FeatureStore__Group_5__0");
			builder.put(grammarAccess.getFeatureStoreAccess().getGroup_5_2(), "rule__FeatureStore__Group_5_2__0");
			builder.put(grammarAccess.getFeatureStoreAccess().getGroup_6(), "rule__FeatureStore__Group_6__0");
			builder.put(grammarAccess.getFeatureStoreAccess().getGroup_6_3(), "rule__FeatureStore__Group_6_3__0");
			builder.put(grammarAccess.getEntityAccess().getGroup(), "rule__Entity__Group__0");
			builder.put(grammarAccess.getEntityAccess().getGroup_4(), "rule__Entity__Group_4__0");
			builder.put(grammarAccess.getFeatureAccess().getGroup(), "rule__Feature__Group__0");
			builder.put(grammarAccess.getFeatureAccess().getGroup_1(), "rule__Feature__Group_1__0");
			builder.put(grammarAccess.getFeatureAccess().getGroup_2(), "rule__Feature__Group_2__0");
			builder.put(grammarAccess.getFeatureAccess().getGroup_2_1(), "rule__Feature__Group_2_1__0");
			builder.put(grammarAccess.getFeatureAccess().getGroup_2_1_3(), "rule__Feature__Group_2_1_3__0");
			builder.put(grammarAccess.getFeatureAccess().getGroup_2_2(), "rule__Feature__Group_2_2__0");
			builder.put(grammarAccess.getFeatureAccess().getGroup_2_2_4(), "rule__Feature__Group_2_2_4__0");
			builder.put(grammarAccess.getPredictionAccess().getGroup(), "rule__Prediction__Group__0");
			builder.put(grammarAccess.getPredictionAccess().getGroup_2(), "rule__Prediction__Group_2__0");
			builder.put(grammarAccess.getLabelAccess().getGroup(), "rule__Label__Group__0");
			builder.put(grammarAccess.getLabelAccess().getGroup_2(), "rule__Label__Group_2__0");
			builder.put(grammarAccess.getRequestDataAccess().getGroup(), "rule__RequestData__Group__0");
			builder.put(grammarAccess.getKeyAccess().getGroup(), "rule__Key__Group__0");
			builder.put(grammarAccess.getDeploymentAccess().getGroup(), "rule__Deployment__Group__0");
			builder.put(grammarAccess.getDeploymentAccess().getGroup_5(), "rule__Deployment__Group_5__0");
			builder.put(grammarAccess.getDeploymentAccess().getGroup_5_2(), "rule__Deployment__Group_5_2__0");
			builder.put(grammarAccess.getBaseAlgorithmAccess().getGroup(), "rule__BaseAlgorithm__Group__0");
			builder.put(grammarAccess.getBaseAlgorithmAccess().getGroup_3(), "rule__BaseAlgorithm__Group_3__0");
			builder.put(grammarAccess.getBaseAlgorithmAccess().getGroup_4(), "rule__BaseAlgorithm__Group_4__0");
			builder.put(grammarAccess.getBaseAlgorithmAccess().getGroup_5(), "rule__BaseAlgorithm__Group_5__0");
			builder.put(grammarAccess.getBaseAlgorithmAccess().getGroup_6(), "rule__BaseAlgorithm__Group_6__0");
			builder.put(grammarAccess.getBaseAlgorithmAccess().getGroup_6_3(), "rule__BaseAlgorithm__Group_6_3__0");
			builder.put(grammarAccess.getBaseAlgorithmAccess().getGroup_7(), "rule__BaseAlgorithm__Group_7__0");
			builder.put(grammarAccess.getBaseAlgorithmAccess().getGroup_7_2(), "rule__BaseAlgorithm__Group_7_2__0");
			builder.put(grammarAccess.getHigherOrderAlgorithmAccess().getGroup(), "rule__HigherOrderAlgorithm__Group__0");
			builder.put(grammarAccess.getHigherOrderAlgorithmAccess().getGroup_4(), "rule__HigherOrderAlgorithm__Group_4__0");
			builder.put(grammarAccess.getHigherOrderAlgorithmAccess().getGroup_5(), "rule__HigherOrderAlgorithm__Group_5__0");
			builder.put(grammarAccess.getHigherOrderAlgorithmAccess().getGroup_6(), "rule__HigherOrderAlgorithm__Group_6__0");
			builder.put(grammarAccess.getHigherOrderAlgorithmAccess().getGroup_7(), "rule__HigherOrderAlgorithm__Group_7__0");
			builder.put(grammarAccess.getHigherOrderAlgorithmAccess().getGroup_7_2(), "rule__HigherOrderAlgorithm__Group_7_2__0");
			builder.put(grammarAccess.getBaseAlgorithmRuntimeAccess().getGroup(), "rule__BaseAlgorithmRuntime__Group__0");
			builder.put(grammarAccess.getBaseAlgorithmRuntimeAccess().getGroup_4(), "rule__BaseAlgorithmRuntime__Group_4__0");
			builder.put(grammarAccess.getHigherOrderAlgorithmRuntimeAccess().getGroup(), "rule__HigherOrderAlgorithmRuntime__Group__0");
			builder.put(grammarAccess.getHigherOrderAlgorithmRuntimeAccess().getGroup_4(), "rule__HigherOrderAlgorithmRuntime__Group_4__0");
			builder.put(grammarAccess.getBaseAlgorithmExecutionAccess().getGroup(), "rule__BaseAlgorithmExecution__Group__0");
			builder.put(grammarAccess.getBaseAlgorithmExecutionAccess().getGroup_4(), "rule__BaseAlgorithmExecution__Group_4__0");
			builder.put(grammarAccess.getBaseAlgorithmExecutionAccess().getGroup_5(), "rule__BaseAlgorithmExecution__Group_5__0");
			builder.put(grammarAccess.getBaseAlgorithmExecutionAccess().getGroup_5_5(), "rule__BaseAlgorithmExecution__Group_5_5__0");
			builder.put(grammarAccess.getBaseAlgorithmExecutionAccess().getGroup_6(), "rule__BaseAlgorithmExecution__Group_6__0");
			builder.put(grammarAccess.getBaseAlgorithmExecutionAccess().getGroup_6_5(), "rule__BaseAlgorithmExecution__Group_6_5__0");
			builder.put(grammarAccess.getBaseAlgorithmExecutionAccess().getGroup_7(), "rule__BaseAlgorithmExecution__Group_7__0");
			builder.put(grammarAccess.getBaseAlgorithmExecutionAccess().getGroup_7_2(), "rule__BaseAlgorithmExecution__Group_7_2__0");
			builder.put(grammarAccess.getBaseAlgorithmExecutionAccess().getGroup_8(), "rule__BaseAlgorithmExecution__Group_8__0");
			builder.put(grammarAccess.getBaseAlgorithmExecutionAccess().getGroup_8_3(), "rule__BaseAlgorithmExecution__Group_8_3__0");
			builder.put(grammarAccess.getHigherOrderAlgorithmExecutionAccess().getGroup(), "rule__HigherOrderAlgorithmExecution__Group__0");
			builder.put(grammarAccess.getHigherOrderAlgorithmExecutionAccess().getGroup_4(), "rule__HigherOrderAlgorithmExecution__Group_4__0");
			builder.put(grammarAccess.getHigherOrderAlgorithmExecutionAccess().getGroup_5(), "rule__HigherOrderAlgorithmExecution__Group_5__0");
			builder.put(grammarAccess.getHigherOrderAlgorithmExecutionAccess().getGroup_6(), "rule__HigherOrderAlgorithmExecution__Group_6__0");
			builder.put(grammarAccess.getHigherOrderAlgorithmExecutionAccess().getGroup_6_2(), "rule__HigherOrderAlgorithmExecution__Group_6_2__0");
			builder.put(grammarAccess.getHigherOrderAlgorithmExecutionAccess().getGroup_7(), "rule__HigherOrderAlgorithmExecution__Group_7__0");
			builder.put(grammarAccess.getHigherOrderAlgorithmExecutionAccess().getGroup_8(), "rule__HigherOrderAlgorithmExecution__Group_8__0");
			builder.put(grammarAccess.getHigherOrderAlgorithmExecutionAccess().getGroup_9(), "rule__HigherOrderAlgorithmExecution__Group_9__0");
			builder.put(grammarAccess.getHigherOrderAlgorithmExecutionAccess().getGroup_9_3(), "rule__HigherOrderAlgorithmExecution__Group_9_3__0");
			builder.put(grammarAccess.getActionExecutionEntryAccess().getGroup(), "rule__ActionExecutionEntry__Group__0");
			builder.put(grammarAccess.getTriggerGroupAccess().getGroup(), "rule__TriggerGroup__Group__0");
			builder.put(grammarAccess.getTriggerGroupAccess().getGroup_3(), "rule__TriggerGroup__Group_3__0");
			builder.put(grammarAccess.getTriggerGroupAccess().getGroup_6(), "rule__TriggerGroup__Group_6__0");
			builder.put(grammarAccess.getCompositeTriggerAccess().getGroup(), "rule__CompositeTrigger__Group__0");
			builder.put(grammarAccess.getCompositeTriggerAccess().getGroup_1_0(), "rule__CompositeTrigger__Group_1_0__0");
			builder.put(grammarAccess.getCompositeTriggerAccess().getGroup_1_1(), "rule__CompositeTrigger__Group_1_1__0");
			builder.put(grammarAccess.getCompositeTriggerAccess().getGroup_1_2(), "rule__CompositeTrigger__Group_1_2__0");
			builder.put(grammarAccess.getCompositeTriggerAccess().getGroup_1_3(), "rule__CompositeTrigger__Group_1_3__0");
			builder.put(grammarAccess.getTemporalTriggerAccess().getGroup_0(), "rule__TemporalTrigger__Group_0__0");
			builder.put(grammarAccess.getTemporalTriggerAccess().getGroup_0_1(), "rule__TemporalTrigger__Group_0_1__0");
			builder.put(grammarAccess.getSampleBasedTriggerAccess().getGroup(), "rule__SampleBasedTrigger__Group__0");
			builder.put(grammarAccess.getPredictionBasedTriggerAccess().getGroup(), "rule__PredictionBasedTrigger__Group__0");
			builder.put(grammarAccess.getLabelBasedTriggerAccess().getGroup(), "rule__LabelBasedTrigger__Group__0");
			builder.put(grammarAccess.getActionAccess().getGroup(), "rule__Action__Group__0");
			builder.put(grammarAccess.getActionAccess().getGroup_4(), "rule__Action__Group_4__0");
			builder.put(grammarAccess.getActionAccess().getGroup_5(), "rule__Action__Group_5__0");
			builder.put(grammarAccess.getActionAccess().getGroup_5_2(), "rule__Action__Group_5_2__0");
			builder.put(grammarAccess.getParameterAccess().getGroup(), "rule__Parameter__Group__0");
			builder.put(grammarAccess.getParameterValueEntryAccess().getGroup(), "rule__ParameterValueEntry__Group__0");
			builder.put(grammarAccess.getActionExecutionAccess().getGroup(), "rule__ActionExecution__Group__0");
			builder.put(grammarAccess.getActionExecutionAccess().getGroup_4(), "rule__ActionExecution__Group_4__0");
			builder.put(grammarAccess.getActionExecutionAccess().getGroup_4_0(), "rule__ActionExecution__Group_4_0__0");
			builder.put(grammarAccess.getActionExecutionAccess().getGroup_4_1(), "rule__ActionExecution__Group_4_1__0");
			builder.put(grammarAccess.getActionExecutionAccess().getGroup_4_1_3(), "rule__ActionExecution__Group_4_1_3__0");
			builder.put(grammarAccess.getEIntegerObjectAccess().getGroup(), "rule__EIntegerObject__Group__0");
			builder.put(grammarAccess.getPlatformAccess().getFeatureStoreAssignment_0(), "rule__Platform__FeatureStoreAssignment_0");
			builder.put(grammarAccess.getPlatformAccess().getMlModelsAssignment_1(), "rule__Platform__MlModelsAssignment_1");
			builder.put(grammarAccess.getPlatformAccess().getDeploymentsAssignment_2(), "rule__Platform__DeploymentsAssignment_2");
			builder.put(grammarAccess.getPlatformAccess().getAlgorithmsAssignment_3(), "rule__Platform__AlgorithmsAssignment_3");
			builder.put(grammarAccess.getPlatformAccess().getAlgorithmRuntimesAssignment_4(), "rule__Platform__AlgorithmRuntimesAssignment_4");
			builder.put(grammarAccess.getPlatformAccess().getActionsAssignment_5(), "rule__Platform__ActionsAssignment_5");
			builder.put(grammarAccess.getModelAccess().getNameAssignment_2(), "rule__Model__NameAssignment_2");
			builder.put(grammarAccess.getModelAccess().getInputsAssignment_5(), "rule__Model__InputsAssignment_5");
			builder.put(grammarAccess.getModelAccess().getInputsAssignment_6_1(), "rule__Model__InputsAssignment_6_1");
			builder.put(grammarAccess.getModelAccess().getOutputAssignment_8(), "rule__Model__OutputAssignment_8");
			builder.put(grammarAccess.getFeatureStoreAccess().getFeaturesAssignment_3_1(), "rule__FeatureStore__FeaturesAssignment_3_1");
			builder.put(grammarAccess.getFeatureStoreAccess().getFeaturesAssignment_3_2_1(), "rule__FeatureStore__FeaturesAssignment_3_2_1");
			builder.put(grammarAccess.getFeatureStoreAccess().getEntitiesAssignment_4_1(), "rule__FeatureStore__EntitiesAssignment_4_1");
			builder.put(grammarAccess.getFeatureStoreAccess().getEntitiesAssignment_4_2_1(), "rule__FeatureStore__EntitiesAssignment_4_2_1");
			builder.put(grammarAccess.getFeatureStoreAccess().getLabelsAssignment_5_1(), "rule__FeatureStore__LabelsAssignment_5_1");
			builder.put(grammarAccess.getFeatureStoreAccess().getLabelsAssignment_5_2_1(), "rule__FeatureStore__LabelsAssignment_5_2_1");
			builder.put(grammarAccess.getFeatureStoreAccess().getRequestDataAssignment_6_2(), "rule__FeatureStore__RequestDataAssignment_6_2");
			builder.put(grammarAccess.getFeatureStoreAccess().getRequestDataAssignment_6_3_1(), "rule__FeatureStore__RequestDataAssignment_6_3_1");
			builder.put(grammarAccess.getEntityAccess().getNameAssignment_0(), "rule__Entity__NameAssignment_0");
			builder.put(grammarAccess.getEntityAccess().getKeysAssignment_3(), "rule__Entity__KeysAssignment_3");
			builder.put(grammarAccess.getEntityAccess().getKeysAssignment_4_1(), "rule__Entity__KeysAssignment_4_1");
			builder.put(grammarAccess.getFeatureAccess().getNameAssignment_0(), "rule__Feature__NameAssignment_0");
			builder.put(grammarAccess.getFeatureAccess().getTypeAssignment_1_1(), "rule__Feature__TypeAssignment_1_1");
			builder.put(grammarAccess.getFeatureAccess().getEntitiesAssignment_2_1_2(), "rule__Feature__EntitiesAssignment_2_1_2");
			builder.put(grammarAccess.getFeatureAccess().getEntitiesAssignment_2_1_3_1(), "rule__Feature__EntitiesAssignment_2_1_3_1");
			builder.put(grammarAccess.getFeatureAccess().getRequestDataAssignment_2_2_3(), "rule__Feature__RequestDataAssignment_2_2_3");
			builder.put(grammarAccess.getFeatureAccess().getRequestDataAssignment_2_2_4_1(), "rule__Feature__RequestDataAssignment_2_2_4_1");
			builder.put(grammarAccess.getPredictionAccess().getNameAssignment_1(), "rule__Prediction__NameAssignment_1");
			builder.put(grammarAccess.getPredictionAccess().getLabelAssignment_2_1(), "rule__Prediction__LabelAssignment_2_1");
			builder.put(grammarAccess.getLabelAccess().getNameAssignment_1(), "rule__Label__NameAssignment_1");
			builder.put(grammarAccess.getLabelAccess().getTypeAssignment_2_1(), "rule__Label__TypeAssignment_2_1");
			builder.put(grammarAccess.getRequestDataAccess().getNameAssignment_1(), "rule__RequestData__NameAssignment_1");
			builder.put(grammarAccess.getKeyAccess().getNameAssignment_1(), "rule__Key__NameAssignment_1");
			builder.put(grammarAccess.getDeploymentAccess().getNameAssignment_1(), "rule__Deployment__NameAssignment_1");
			builder.put(grammarAccess.getDeploymentAccess().getMlModelAssignment_4(), "rule__Deployment__MlModelAssignment_4");
			builder.put(grammarAccess.getDeploymentAccess().getInputsAssignment_5_1(), "rule__Deployment__InputsAssignment_5_1");
			builder.put(grammarAccess.getDeploymentAccess().getInputsAssignment_5_2_1(), "rule__Deployment__InputsAssignment_5_2_1");
			builder.put(grammarAccess.getDeploymentAccess().getAlgorithmexecutionsAssignment_6(), "rule__Deployment__AlgorithmexecutionsAssignment_6");
			builder.put(grammarAccess.getDeploymentAccess().getActionExecutionsAssignment_7(), "rule__Deployment__ActionExecutionsAssignment_7");
			builder.put(grammarAccess.getDeploymentAccess().getTriggerGroupsAssignment_8(), "rule__Deployment__TriggerGroupsAssignment_8");
			builder.put(grammarAccess.getBaseAlgorithmAccess().getNameAssignment_1(), "rule__BaseAlgorithm__NameAssignment_1");
			builder.put(grammarAccess.getBaseAlgorithmAccess().getCodebaseAssignment_3_1(), "rule__BaseAlgorithm__CodebaseAssignment_3_1");
			builder.put(grammarAccess.getBaseAlgorithmAccess().getRuntimeAssignment_4_1(), "rule__BaseAlgorithm__RuntimeAssignment_4_1");
			builder.put(grammarAccess.getBaseAlgorithmAccess().getDriftLevelsAssignment_5_2(), "rule__BaseAlgorithm__DriftLevelsAssignment_5_2");
			builder.put(grammarAccess.getBaseAlgorithmAccess().getStrictAssignment_6_1(), "rule__BaseAlgorithm__StrictAssignment_6_1");
			builder.put(grammarAccess.getBaseAlgorithmAccess().getSupportedTypesAssignment_6_2(), "rule__BaseAlgorithm__SupportedTypesAssignment_6_2");
			builder.put(grammarAccess.getBaseAlgorithmAccess().getSupportedTypesAssignment_6_3_1(), "rule__BaseAlgorithm__SupportedTypesAssignment_6_3_1");
			builder.put(grammarAccess.getBaseAlgorithmAccess().getAdditionalParametersAssignment_7_1(), "rule__BaseAlgorithm__AdditionalParametersAssignment_7_1");
			builder.put(grammarAccess.getBaseAlgorithmAccess().getAdditionalParametersAssignment_7_2_1(), "rule__BaseAlgorithm__AdditionalParametersAssignment_7_2_1");
			builder.put(grammarAccess.getHigherOrderAlgorithmAccess().getNameAssignment_2(), "rule__HigherOrderAlgorithm__NameAssignment_2");
			builder.put(grammarAccess.getHigherOrderAlgorithmAccess().getCodebaseAssignment_4_1(), "rule__HigherOrderAlgorithm__CodebaseAssignment_4_1");
			builder.put(grammarAccess.getHigherOrderAlgorithmAccess().getRuntimeAssignment_5_1(), "rule__HigherOrderAlgorithm__RuntimeAssignment_5_1");
			builder.put(grammarAccess.getHigherOrderAlgorithmAccess().getDriftLevelsAssignment_6_2(), "rule__HigherOrderAlgorithm__DriftLevelsAssignment_6_2");
			builder.put(grammarAccess.getHigherOrderAlgorithmAccess().getAdditionalParametersAssignment_7_1(), "rule__HigherOrderAlgorithm__AdditionalParametersAssignment_7_1");
			builder.put(grammarAccess.getHigherOrderAlgorithmAccess().getAdditionalParametersAssignment_7_2_1(), "rule__HigherOrderAlgorithm__AdditionalParametersAssignment_7_2_1");
			builder.put(grammarAccess.getBaseAlgorithmRuntimeAccess().getNameAssignment_2(), "rule__BaseAlgorithmRuntime__NameAssignment_2");
			builder.put(grammarAccess.getBaseAlgorithmRuntimeAccess().getEndpointAssignment_4_1(), "rule__BaseAlgorithmRuntime__EndpointAssignment_4_1");
			builder.put(grammarAccess.getHigherOrderAlgorithmRuntimeAccess().getNameAssignment_2(), "rule__HigherOrderAlgorithmRuntime__NameAssignment_2");
			builder.put(grammarAccess.getHigherOrderAlgorithmRuntimeAccess().getEndpointAssignment_4_1(), "rule__HigherOrderAlgorithmRuntime__EndpointAssignment_4_1");
			builder.put(grammarAccess.getBaseAlgorithmExecutionAccess().getNameAssignment_2(), "rule__BaseAlgorithmExecution__NameAssignment_2");
			builder.put(grammarAccess.getBaseAlgorithmExecutionAccess().getExecutableAssignment_4_1(), "rule__BaseAlgorithmExecution__ExecutableAssignment_4_1");
			builder.put(grammarAccess.getBaseAlgorithmExecutionAccess().getCurrentIOValuesAssignment_5_4(), "rule__BaseAlgorithmExecution__CurrentIOValuesAssignment_5_4");
			builder.put(grammarAccess.getBaseAlgorithmExecutionAccess().getCurrentIOValuesAssignment_5_5_1(), "rule__BaseAlgorithmExecution__CurrentIOValuesAssignment_5_5_1");
			builder.put(grammarAccess.getBaseAlgorithmExecutionAccess().getHistoricIOValuesAssignment_6_4(), "rule__BaseAlgorithmExecution__HistoricIOValuesAssignment_6_4");
			builder.put(grammarAccess.getBaseAlgorithmExecutionAccess().getHistoricIOValuesAssignment_6_5_1(), "rule__BaseAlgorithmExecution__HistoricIOValuesAssignment_6_5_1");
			builder.put(grammarAccess.getBaseAlgorithmExecutionAccess().getActionExecutionMapAssignment_7_1(), "rule__BaseAlgorithmExecution__ActionExecutionMapAssignment_7_1");
			builder.put(grammarAccess.getBaseAlgorithmExecutionAccess().getActionExecutionMapAssignment_7_2_1(), "rule__BaseAlgorithmExecution__ActionExecutionMapAssignment_7_2_1");
			builder.put(grammarAccess.getBaseAlgorithmExecutionAccess().getParameterValueMapAssignment_8_2(), "rule__BaseAlgorithmExecution__ParameterValueMapAssignment_8_2");
			builder.put(grammarAccess.getBaseAlgorithmExecutionAccess().getParameterValueMapAssignment_8_3_1(), "rule__BaseAlgorithmExecution__ParameterValueMapAssignment_8_3_1");
			builder.put(grammarAccess.getHigherOrderAlgorithmExecutionAccess().getNameAssignment_2(), "rule__HigherOrderAlgorithmExecution__NameAssignment_2");
			builder.put(grammarAccess.getHigherOrderAlgorithmExecutionAccess().getExecutableAssignment_4_1(), "rule__HigherOrderAlgorithmExecution__ExecutableAssignment_4_1");
			builder.put(grammarAccess.getHigherOrderAlgorithmExecutionAccess().getAlgorithmExecutionAssignment_5_2(), "rule__HigherOrderAlgorithmExecution__AlgorithmExecutionAssignment_5_2");
			builder.put(grammarAccess.getHigherOrderAlgorithmExecutionAccess().getActionExecutionMapAssignment_6_1(), "rule__HigherOrderAlgorithmExecution__ActionExecutionMapAssignment_6_1");
			builder.put(grammarAccess.getHigherOrderAlgorithmExecutionAccess().getActionExecutionMapAssignment_6_2_1(), "rule__HigherOrderAlgorithmExecution__ActionExecutionMapAssignment_6_2_1");
			builder.put(grammarAccess.getHigherOrderAlgorithmExecutionAccess().getMinDataPointsAssignment_7_2(), "rule__HigherOrderAlgorithmExecution__MinDataPointsAssignment_7_2");
			builder.put(grammarAccess.getHigherOrderAlgorithmExecutionAccess().getMaxDataPointsAssignment_8_2(), "rule__HigherOrderAlgorithmExecution__MaxDataPointsAssignment_8_2");
			builder.put(grammarAccess.getHigherOrderAlgorithmExecutionAccess().getParameterValueMapAssignment_9_2(), "rule__HigherOrderAlgorithmExecution__ParameterValueMapAssignment_9_2");
			builder.put(grammarAccess.getHigherOrderAlgorithmExecutionAccess().getParameterValueMapAssignment_9_3_1(), "rule__HigherOrderAlgorithmExecution__ParameterValueMapAssignment_9_3_1");
			builder.put(grammarAccess.getActionExecutionEntryAccess().getKeyAssignment_1(), "rule__ActionExecutionEntry__KeyAssignment_1");
			builder.put(grammarAccess.getActionExecutionEntryAccess().getValueAssignment_3(), "rule__ActionExecutionEntry__ValueAssignment_3");
			builder.put(grammarAccess.getTriggerGroupAccess().getCompositeTriggersAssignment_2(), "rule__TriggerGroup__CompositeTriggersAssignment_2");
			builder.put(grammarAccess.getTriggerGroupAccess().getCompositeTriggersAssignment_3_1(), "rule__TriggerGroup__CompositeTriggersAssignment_3_1");
			builder.put(grammarAccess.getTriggerGroupAccess().getTargetsAssignment_5(), "rule__TriggerGroup__TargetsAssignment_5");
			builder.put(grammarAccess.getTriggerGroupAccess().getTargetsAssignment_6_1(), "rule__TriggerGroup__TargetsAssignment_6_1");
			builder.put(grammarAccess.getCompositeTriggerAccess().getTtAssignment_1_0_1(), "rule__CompositeTrigger__TtAssignment_1_0_1");
			builder.put(grammarAccess.getCompositeTriggerAccess().getStAssignment_1_1_1(), "rule__CompositeTrigger__StAssignment_1_1_1");
			builder.put(grammarAccess.getCompositeTriggerAccess().getPtAssignment_1_2_1(), "rule__CompositeTrigger__PtAssignment_1_2_1");
			builder.put(grammarAccess.getCompositeTriggerAccess().getLtAssignment_1_3_1(), "rule__CompositeTrigger__LtAssignment_1_3_1");
			builder.put(grammarAccess.getTemporalTriggerAccess().getFrequencyAssignment_0_1_1(), "rule__TemporalTrigger__FrequencyAssignment_0_1_1");
			builder.put(grammarAccess.getTemporalTriggerAccess().getCronStringAssignment_1(), "rule__TemporalTrigger__CronStringAssignment_1");
			builder.put(grammarAccess.getSampleBasedTriggerAccess().getFrequencyAssignment_1(), "rule__SampleBasedTrigger__FrequencyAssignment_1");
			builder.put(grammarAccess.getPredictionBasedTriggerAccess().getFrequencyAssignment_1(), "rule__PredictionBasedTrigger__FrequencyAssignment_1");
			builder.put(grammarAccess.getLabelBasedTriggerAccess().getFrequencyAssignment_1(), "rule__LabelBasedTrigger__FrequencyAssignment_1");
			builder.put(grammarAccess.getActionAccess().getNameAssignment_2(), "rule__Action__NameAssignment_2");
			builder.put(grammarAccess.getActionAccess().getEndpointAssignment_4_1(), "rule__Action__EndpointAssignment_4_1");
			builder.put(grammarAccess.getActionAccess().getAdditionalParametersAssignment_5_1(), "rule__Action__AdditionalParametersAssignment_5_1");
			builder.put(grammarAccess.getActionAccess().getAdditionalParametersAssignment_5_2_1(), "rule__Action__AdditionalParametersAssignment_5_2_1");
			builder.put(grammarAccess.getParameterAccess().getMandatoryAssignment_1(), "rule__Parameter__MandatoryAssignment_1");
			builder.put(grammarAccess.getParameterAccess().getNameAssignment_2(), "rule__Parameter__NameAssignment_2");
			builder.put(grammarAccess.getParameterAccess().getTypeAssignment_4(), "rule__Parameter__TypeAssignment_4");
			builder.put(grammarAccess.getParameterValueEntryAccess().getKeyAssignment_1(), "rule__ParameterValueEntry__KeyAssignment_1");
			builder.put(grammarAccess.getParameterValueEntryAccess().getValueAssignment_3(), "rule__ParameterValueEntry__ValueAssignment_3");
			builder.put(grammarAccess.getActionExecutionAccess().getNameAssignment_2(), "rule__ActionExecution__NameAssignment_2");
			builder.put(grammarAccess.getActionExecutionAccess().getExecutableAssignment_4_0_1(), "rule__ActionExecution__ExecutableAssignment_4_0_1");
			builder.put(grammarAccess.getActionExecutionAccess().getParameterValueMapAssignment_4_1_2(), "rule__ActionExecution__ParameterValueMapAssignment_4_1_2");
			builder.put(grammarAccess.getActionExecutionAccess().getParameterValueMapAssignment_4_1_3_1(), "rule__ActionExecution__ParameterValueMapAssignment_4_1_3_1");
			builder.put(grammarAccess.getCompositeTriggerAccess().getUnorderedGroup_1(), "rule__CompositeTrigger__UnorderedGroup_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private PanoptesXGrammarAccess grammarAccess;

	@Override
	protected InternalPanoptesXParser createParser() {
		InternalPanoptesXParser result = new InternalPanoptesXParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public PanoptesXGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(PanoptesXGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
