/*
 * generated by Xtext 2.25.0
 */
package org.lowcomote.panoptes.validation;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.validation.Check;

import panoptesDSL.Execution;
import panoptesDSL.HigherOrderAlgorithmExecution;
import panoptesDSL.PanoptesDSLPackage;
import panoptesDSL.Parameter;
import panoptesDSL.parameterValueEntry;
import panoptesDSL.ActionExecution;
import panoptesDSL.BaseAlgorithmExecution;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class PanoptesXValidator extends AbstractPanoptesXValidator {
	public static final String MANDTORY_PARAMETER_MISSING = "mandatoryParameterMissing";
	public static final String UNKNOWN_PARAMETER = "unknownParameter";
	public static final String WRONG_TYPE = "wrongType";
	
	@Check
	public void checkFeatureTypes(Execution execution) {
		//TODO
	}
	
	@Check
	public void checkDeploymentInputs(Execution execution) {
		//TODO
	}
	
	@Check
	public void checkMandatoryParameters(Execution execution) {
		for (Parameter p : getAdditionalParameters(execution)) {
			if (p.isMandatory()) {
				boolean found = false;
				for (parameterValueEntry entry : execution.getParameterValueMap()) {
					if (entry.getKey().equals(p.getName())) {
						found = true;
						break;
					}
				}
				if (!found) {
					error("No value provided for mandatory parameter " + p.getName(),
							PanoptesDSLPackage.Literals.EXECUTION__PARAMETER_VALUE_MAP,
							UNKNOWN_PARAMETER);
				}
			}
		}
	}
	
	@Check
	public void checkUnknownParameters(Execution execution) {
		for (parameterValueEntry entry : execution.getParameterValueMap()) {
			boolean found = false;
			for (Parameter p : getAdditionalParameters(execution)) {
				if (entry.getKey().equals(p.getName())) {
					found = true;
					break;
				}
			}
			if (!found) {
				warning("Unknown parameter " + entry.getKey(),
						PanoptesDSLPackage.Literals.EXECUTION__PARAMETER_VALUE_MAP,
						MANDTORY_PARAMETER_MISSING);
			}
		}
	}
	
	@Check
	public void checkParameterTypes(Execution execution) {
		for (parameterValueEntry entry : execution.getParameterValueMap()) {
			Parameter parameter = null;
			for (Parameter p : getAdditionalParameters(execution)) {
				if (entry.getKey().equals(p.getName())) {
					parameter = p;
					break;
				}
			}
			if (parameter != null & parameter.getType()!=null) {
				switch(parameter.getType().getLiteral()) {
				case("Integer"):
					try {
						Integer.parseInt(entry.getValue());
					}
					catch(Exception e){
						error("Value of parameter " + entry.getKey() + " is not a valid Integer",
								PanoptesDSLPackage.Literals.EXECUTION__PARAMETER_VALUE_MAP,
								WRONG_TYPE);
					}
					break;
				case("Boolean"):
					if ( !entry.getValue().equals("true")  & !entry.getValue().equals("false")){
							error("Value of parameter " + entry.getKey() + " is not a valid Boolean",
									PanoptesDSLPackage.Literals.EXECUTION__PARAMETER_VALUE_MAP,
									WRONG_TYPE);
					}
					break;
				case("Real"):
					try {
						Double.parseDouble(entry.getValue());
					}
					catch(Exception e) {
						error("Value of parameter " + entry.getKey() + " is not a valid Real",
								PanoptesDSLPackage.Literals.EXECUTION__PARAMETER_VALUE_MAP,
								WRONG_TYPE);
					}
					break;
				}
			}
		}
	}
	
	private EList<Parameter> getAdditionalParameters(EObject execution){
		EList<Parameter> parameters = null;
		if (execution.eClass().getClassifierID()==PanoptesDSLPackage.BASE_ALGORITHM_EXECUTION){
			parameters = ((BaseAlgorithmExecution)execution).getAlgorithm().getAdditionalParameters();
		}
		else if (execution.eClass().getClassifierID()==PanoptesDSLPackage.HIGHER_ORDER_ALGORITHM_EXECUTION) {
			parameters = ((HigherOrderAlgorithmExecution)execution).getAlgorithm().getAdditionalParameters();
		}
		else if (execution.eClass().getClassifierID()==PanoptesDSLPackage.ACTION_EXECUTION) {
			parameters = ((ActionExecution)execution).getAction().getAdditionalParameters();
		}
		return parameters;
	}
}
