/*
 * generated by Xtext 2.25.0
 */
package org.lowcomote.panoptes;

import org.eclipse.xtext.naming.IQualifiedNameProvider;
import org.eclipse.xtext.naming.SimpleNameProvider;

/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class PanoptesXRuntimeModule extends AbstractPanoptesXRuntimeModule {

//	public Class<? extends IFragmentProvider> bindIFragmentProvider() {
//		return QualifiedNameFragmentProvider.class;
//	}
	
	public Class<? extends IQualifiedNameProvider> bindIQualifiedNameProvider(){
		return SimpleNameProvider.class;
	}

}
