/*
 * generated by Xtext 2.25.0
 */
package org.lowcomote.panoptes;

/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class PanoptesXRuntimeModule extends AbstractPanoptesXRuntimeModule {

//	public Class<? extends IFragmentProvider> bindIFragmentProvider() {
//		return QualifiedNameFragmentProvider.class;
//	}

}
