/*
 * generated by Xtext 2.25.0
 */
package org.lowcomote.panoptes;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class PanoptesXStandaloneSetup extends PanoptesXStandaloneSetupGenerated {

	public static void doSetup() {
		new PanoptesXStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
