/*
 * generated by Xtext 2.25.0
 */
package org.lowcomote.panoptes.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class PanoptesXAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/lowcomote/panoptes/parser/antlr/internal/InternalPanoptesX.tokens");
	}
}
