/*
 * generated by Xtext 2.25.0
 */
package org.lowcomote.panoptes.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.lowcomote.panoptes.parser.antlr.internal.InternalPanoptesXParser;
import org.lowcomote.panoptes.services.PanoptesXGrammarAccess;

public class PanoptesXParser extends AbstractAntlrParser {

	@Inject
	private PanoptesXGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalPanoptesXParser createParser(XtextTokenStream stream) {
		return new InternalPanoptesXParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Platform";
	}

	public PanoptesXGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(PanoptesXGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
