/*
 * generated by Xtext 2.25.0
 */
package org.lowcomote.panoptes.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractPanoptesXScopeProvider extends DelegatingScopeProvider {
}
