/*
 * generated by Xtext 2.25.0
 */
package org.lowcomote.panoptes.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class PanoptesXUiModule extends AbstractPanoptesXUiModule {

	public PanoptesXUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
