/*
 * generated by Xtext 2.25.0
 */
package org.lowcomote.panoptes.web;

import org.eclipse.xtext.web.server.persistence.FileResourceHandler;
import org.eclipse.xtext.web.server.persistence.IResourceBaseProvider;
import org.eclipse.xtext.web.server.persistence.IServerResourceHandler;

import com.google.inject.Binder;

/**
 * Use this class to register additional components to be used within the web application.
 */
public class PanoptesXWebModule extends AbstractPanoptesXWebModule {
	private  IResourceBaseProvider resourceBaseProvider;
	
	public void configureResourceBaseProvider(Binder binder) {
		if (resourceBaseProvider != null) {
			binder.bind(IResourceBaseProvider.class).toInstance(resourceBaseProvider);
		}
	}

	public Class<? extends IServerResourceHandler> bindIServerResourceHandler() {
		return FileResourceHandler.class;
	}
	
	public PanoptesXWebModule(IResourceBaseProvider resourceBaseProvider) {
		this.resourceBaseProvider = resourceBaseProvider;
	}
}
