/*
 * generated by Xtext 2.25.0
 */
package org.lowcomote.panoptes.web;

import com.google.inject.Injector;

import panoptesDSL.PanoptesDSLPackage;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;

import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.util.DisposableRegistry;
import org.eclipse.xtext.web.server.persistence.IResourceBaseProvider;
import org.eclipse.xtext.web.server.persistence.ResourceBaseProviderImpl;
import org.eclipse.xtext.web.servlet.XtextServlet;

/**
 * Deploy this class into a servlet container to enable DSL-specific services.
 */
@WebServlet(name = "XtextServices", urlPatterns = "/xtext-service/*")
public class PanoptesXServlet extends XtextServlet {
	
	private static final long serialVersionUID = 1L;
	
	DisposableRegistry disposableRegistry;
	
	public void init() throws ServletException {
		super.init();
		EPackage.Registry.INSTANCE.put(PanoptesDSLPackage.eNS_URI, PanoptesDSLPackage.eINSTANCE);
		IResourceBaseProvider resourceBaseProvider = new ResourceBaseProviderImpl("./resources");
		Injector injector = new PanoptesXWebSetup(resourceBaseProvider).createInjectorAndDoEMFRegistration();
		this.disposableRegistry = injector.getInstance(DisposableRegistry.class);
	}
	
	public void destroy() {
		if (disposableRegistry != null) {
			disposableRegistry.dispose();
			disposableRegistry = null;
		}
		super.destroy();
	}
	
}
