/*
 * generated by Xtext 2.25.0
 */
package org.lowcomote.panoptes.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.lowcomote.panoptes.PanoptesXRuntimeModule;
import org.lowcomote.panoptes.PanoptesXStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class PanoptesXIdeSetup extends PanoptesXStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new PanoptesXRuntimeModule(), new PanoptesXIdeModule()));
	}
	
}
