/*
 * generated by Xtext 2.25.0
 */
package org.lowcomote.panoptes.ide;


/**
 * Use this class to register ide components.
 */
public class PanoptesXIdeModule extends AbstractPanoptesXIdeModule {
}
